@startuml

hide members

class Display
class Output
class CoockController
class PowerTube
class Timer
class Ligth
class UserInterface
class Door
class Button 

CoockController <-d-> Timer
CoockController -l-> PowerTube
CoockController -u-> Display
CoockController <-r-> UserInterface
  UserInterface -l-> Display
  UserInterface -u-> Ligth

 
 UserInterface .d.> Button
 UserInterface .d.> Door
 Door -r-> UserInterface
 Button -d-> UserInterface 

Output <-r- Ligth
Output <-r- Display
Output <-d- PowerTube 


@enduml